# Generated by Django 3.1 on 2020-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField()),
                ('rank', models.ImageField())
            ],
        ),
    ]
