# Generated by Django 3.1 on 2020-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='d.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
