# Generated by Django 3.1 on 2020-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200813_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.CharField(choices=[('agriculture_power_sprayer', 'agriculture_power_sprayer'), ('air_& vacuum pump', 'air & vacuum pump'), ('car washers', 'car washers'), ('compressor', 'compressor'), ('electric motors', 'electric motors'), ('foam gun', 'foam gun'), ('foam tank', 'foam tank'), ('garage equipment & accessories', 'garage equipment & accessories'), ('grease pump', 'grease pump'), ('hi-pressure pump & pipe', 'hi-pressure pump & pipe'), ('impact wrench', 'impact wrench'), ('pneumatic fitting', 'pneumatic fitting'), ('spray gun', 'spray gun'), ('tire inflating gun', 'tire inflating gun'), ('vacuum cleaners', 'vacuum cleaners'), ('welding machine', 'welding machine'), ('agriculture sprayer parts', 'agriculture sprayer parts'), ('hardware_items', 'hardware_items')], default='compressor', max_length=40),
        ),
    ]
