# Generated by Django 3.1 on 2020-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200814_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
